### ISSUE TITLE
TOC exstention allow for numbering

### ISSUE THREAD

**Issue by HackerWithoutACause** [Python-Markdown/markdown#1037]
Is there a way to add numbering to TOC lists like:
```
1. First Header
    1.1 Subheader
    1.2 Second Subheader
2. Last Header
    2.1 Last Header
```

**Comment by mitya57** [comment]
You can achieve this with CSS and counters, see https://stackoverflow.com/q/4098195. That question talks about `<ol>`s, but I believe the same would work with `<ul>`s as well, just add `list-style-type: none` additionally. I have not tried though.

So in my opinion there is nothing to do on Python-Markdown side.

**Comment by HackerWithoutACause** [comment]
Thanks! I didn't know you could do that with CSS.

**Comment by RoyiAvital** [comment]
@mitya57 , Is there a way to set this only for the TOC?
As adding this to the CSS for all lists won't make sense.

**Comment by mitya57** [comment]
@RoyiAvital Just prefix the rules with `.toc`, e.g.:

```html
<style>
.toc ul {
  counter-reset: item;
}
.toc li {
  display: block;
}
.toc li:before {
  content: counters(item, ".") " ";
  counter-increment: item;
}
</style>
```

**Comment by RoyiAvital** [comment]
I tried to get an answer in [Numbered List in a `TOC` Class by Python Markdown](https://stackoverflow.com/questions/67651135).

I hope I will get a robust solution.

**Comment by mitya57** [comment]
I have just tried with four levels of headers and it works fine:

![ReText screenshot](https://user-images.githubusercontent.com/1381584/119236811-1933e880-bb42-11eb-9e00-d0a3363a4cd9.png)

**Comment by RoyiAvital** [comment]
With your permission, How would you also set different font size per level?

**Comment by mitya57** [comment]
A very primitive way:
```css
.toc ul {
  font-size: 16pt;
}
.toc ul ul {
  font-size: 14pt;
}
.toc ul ul ul {
  font-size: 12pt;
}
.toc ul ul ul ul {
  font-size: 10pt;
}
```

But this seems to also work and make size for every next level smaller:
```css
.toc ul {
  font-size: 16pt;
}
.toc ul ul {
  font-size: smaller;
}
```
