### ISSUE TITLE
Can md_in_html be used for a Grid layout?

### ISSUE THREAD

**Issue by Andre601** [Python-Markdown/markdown#1271]
I'm facing a weird issue, where using `markdown` in a `div` for a Grid setup is rendering the first grid section, but not the second one next to it.

As an example, the following setup:
````markdown
<div class="mdx-grid-container" markdown>
<div class="mdx-grid-wrapper">
<div class="mdx-grid-child">

## Getting Started

You can install the library as shown here.

</div>
<div class="mdx-grid-child" markdown>

## Configuration

```
TODO: Install code
```

</div>
</div>
</div>
````

...is rendering like this:
![image](https://user-images.githubusercontent.com/11576465/178123078-045026ce-85e1-429e-99b6-ab6375531ea0.png)

As you can see is the code block rendered, but the H2 header is for whatever reason not.
I'm not sure if any extra steps are required here. I tried with `markdown="1"`, `markdown="block"` and `markdown="span"` but neither did change the result.
I also tried adding the tag to the div section of the second grid block without any success.

Here are the relevant CSS parts if they are of any importance:
```css


/* Grid stuff */

.mdx-grid-container {
    background-color: var(--md-admonition-bg-color);
    padding: 1rem;
}

.mdx-grid-container h2, .mdx-grid-container h3 {
    text-align: center;
    margin-top: 0;
}

.mdx-grid-wrapper {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
}

@media only screen and (max-width: 600px) {
    .mdx-grid-wrapper {
        display: grid;
        grid-template-columns: 1fr;
        gap: 1rem;
    }
}

.mdx-grid-child {
    background-color: var(--md-default-bg-color);
    padding: 0.5rem;
}
```
