### ISSUE TITLE
Abbreviation processing order alternative

### ISSUE THREAD

**Issue by nbanyan** [Python-Markdown/markdown#1465]
Currently the `abbr` extension implements the last definition of an abbreviation.
In MkDocs with the `pymdownx.snippet` extension, a glossary can be auto-appended to Markdown pages.

The problem is that this prevents pages from overriding abbreviations from the glossary.  To circumvent this I've been manually adding the glossary snippet to the top of all pages. But this requires some page specific abbreviations to be declared before the snippet and some after.  As the lists continue to grow this can quickly cause some abbreviations to be incorrect.

**Example of the currently required order:**

In `glossary.md`:
``` markdown title="glossary.md"
*[process]: process definition one
*[ABC]: Abbreviation definition one
*[XYZ]: Abbreviation definition two (newly added)
```

In `page.md`:
``` markdown title="page.md"
*[specialized process]: process definition specialization
--8<-- "glossary.md"
*[XYZ-A]: Unrealized Abbreviation due to change in glossary.md
*[ABC]: Abbreviation definition one redefinition
```
* 'specialized process' must be defined before the snippet so the entire phrase is processed before 'process' is implemented
* 'ABC' must be defined after the snippet otherwise it will be overridden by the glossary definition
* 'XYZ-A' is no longer implemented since the snippet now defines and implements 'XYZ' first

**Proposals:**

* Option 1: An option to have the `abbr` extension only keep/process the first instance of an abbreviation instead of the last.
* Option 2: An option to sort the abbreviation list to process 'superset' abbreviations first to transparently illuminate the issues with terms like the 'specialized process' and 'XYZ-A' in the example.

Both options would allow effective use of auto-append and illuminate the issue of needing to analyze how abbreviations are processed every time one is written and reassessing/adjusting the ordering in pages when a new term is added to the glossary.

The second option would require more processing time, but prevent issues (from Option1) with a page declaring an abbreviation that breaks an abbreviation in an auto-appended glossary.

**Comment by waylan** [comment]
> this requires some page specific abbreviations to be declared before the snippet and some after.

Personally, this is exactly how I would expect to solve this issue, which means we don't need to make any changes. It is not clear to me how this is resulting in incorrect abbreviations. Perhaps an example would help. 

Or are you saying that sometimes you get the order wrong and that results in the errors. If that is the case, then I don't see how your suggested changes would help. You would still need to ensure correct order, even if that order would be different.

In any event, previously, Option 1 of your proposal would have been impractical. However, with the recent refactor of the extension in #1461 (not yet released), it would be relatively easy to implement as there is now a global collection of abbreviations stored as a dict (just check if the entry already exists and skip writing if it does). However, Option 2 would be impossible as a dict cannot have two entries with the same key (the abbreviation is used as the key in the collection).

Personally, I would think that it would make more sense for the proposals to apply to abbreviations being defined programicaly (in Python) rather than by including snippets from other files within the Markdown source. In fact, the recent refactor was implemented with that in mind. It would be relatively simple to add a config option which accepted a dict of predefined abbreviations.

Regardless, personally I have no need for any of this and am not inclined to spend any time working on it. However, if someone else wants to, I would be willing to review a PR.

**Comment by nbanyan** [comment]
Here's an MkDocs example I've put together discussing a use case for `use_first_abbr` and options for how to define a glossary for `abbr`.  In my opinion, if `abbr` can use a global glossary then `use_first_abbr` would be redundant since its purpose is to allow extensions like `pymdownx.snippet` to provide a glossary while still letting pages define their own abbreviations.

[abbr_mkdocs.zip](https://github.com/user-attachments/files/15541218/abbr_mkdocs.zip)

**Comment by waylan** [comment]
I'm sorry, but I don't download files from random people. You need to lay out a simple example (much less complex than anything which requires MkDocs) here in code blocks. You need to make a case for why using the first definition solves a problem that cannot be solved using the last definition. And you need to provide the explanation. Don't assume I will look at your example and suddenly get it.

**Comment by nbanyan** [comment]
Unfortionately the use case is applying a glossary in MkDocs.

### use_first_abbr

PyMdown Extensions has a Snippet extension for inserting sections of files into Markdown.  It provides an `auto_append` option which can paste a glossary file to the end of every page. 

It is for this scenario that I proposed the `use_first_abbr` option so that a page with an auto-appended glossary would still be able to use its own definitions.

``` yaml
markdown_extensions:
  - abbr:
      use_first_abbr: True
  - pymdownx.snippets:
      base_path:
        - docs
      auto_append:
        - glossary.md
      check_paths: true
```

### glossary

I coded the `glossary` option to be a direct replacement for the `auto_append`+`use_first_abbr` combination.  I left both options in the PR because I implemented the `user_first_abbr` first and as a simple alternative if `glossary` is to be put in the backlog for latter. Using the Markdown syntax for the glossary file seemed natural to me from the MkDocs environment.

The only way I can think of to provide a raw object to `abbr` through MkDocs is by having the glossary be a JSON dictionary in **mkdocs.yml**, which looks and feels very cumbersome.  Especially when the list grows past a couple hundred abbreviations.

``` yaml
markdown_extensions:
  - abbr:
      glossary:
        {
          "CNO" : "Chief of Naval Operations",
          "TCP" : "Telemetry & Command Program",
          "HTML" : "Hyper Text Markup Language",
          "W3C" : "World Wide Web Consortium",
          "DOD" : "Department of Defense"
        }
  - pymdownx.snippets:
      base_path:
        - docs
      check_paths: true
  - pymdownx.superfences
```

A possible remediation would be to have **mkdocs.yml** inherit from a **.yml** dedicated to the `abbr` extension, but that requires changing `markdown_extensions` to be a dictionary instead of a list.

``` yaml title="abbr.yml"
markdown_extensions:
  abbr:
    glossary:
      {
        "CNO" : "Chief of Naval Operations",
        "TCP" : "Telemetry & Command Program",
        "HTML" : "Hyper Text Markup Language",
        "W3C" : "World Wide Web Consortium",
        "DOD" : "Department of Defense"
      }
```

``` yaml title="mkdocs.yml"
INHERIT: ../abbr.yml
site_name: ...
...
markdown_extensions:
  pymdownx.snippets:
      base_path:
        - docs
      check_paths: true
  pymdownx.superfences: {}
```

Perhaps adding a `json_glossary` option to accept a dictionary directly and expanding the `glossary` option to also accept a file object would streamline this from both the Python and MkDocs perspectives?
