### ISSUE TITLE
Version 3.8.0 does not render tables within `<center>` paired tags

### ISSUE THREAD

**Issue by 9ao9ai9ar** [Python-Markdown/markdown#1533]
With the following minimal setup running MkDocs 1.6.1:

```yaml
# mkdocs.yml
site_name: test
markdown_extensions:
  - tables
```

```markdown
<!-- index.md -->
<center>
| Heading |
| ------- |
| 1       |
</center>
```

The HTML output is unrendered:

```
| Heading | | ------- | | 1 | 
```

Installing the previous version (3.7.0) of Python-Markdown works, and so does removing the `<center>` paired tags.
